# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a55ef7b61b5b5667afbccab61b45afac58a8c803eb9227d28b15f79e385e997fcb4f25f782965212dcc1e6583a8b62a8c9e17987ef141b554d7cb8d220d5079c

test:
  secret_key_base: 631d4b6c53fe62f52686f5be5a9249ae699d5d91e8440eaa8b8141e89dba5050781dc0d682909be7629c1d7855ee627c030208685574123be530d8bc5e20c23d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
